### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by mateusz** [PTCInc/solr-php-client#3]
Would you be able to [composerise](https://getcomposer.org/doc/02-libraries.md) this package? And the add it to packagist.org so people can pull it in as dependency? :-)

**Comment by mateusz** [comment]
Or alternatively @djimenez would you be keen to add another repo owner, so I could composerise and tag? We depend on your module (literally), and right now we have it committed into our repo which is bad.

**Comment by djimenez** [comment]
A pull request is welcome. It seems like a small but helpful addition. If there are any requirements for tagging to get it properly show up in packagist, it'd be helpful if you include that. Thanks.

**Comment by mateusz** [comment]
Hi @djimenez any news on merging #4 ? :-)

**Comment by djimenez** [comment]
merged, tagged, and packagist is crawling.

**Comment by mateusz** [comment]
Thanks a lot, very helpful!
